//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cars()
        {
            this.repairs_logbook = new HashSet<repairs_logbook>();
            this.trips_logbook = new HashSet<trips_logbook>();
        }
        [Display(Name = "Номер машины")]
        [Range(0, 999, ErrorMessage = "Некорректно введен номер машины")]
        [RegularExpression(@"\d{3}", ErrorMessage = "Некорректно введен номер машины")]
        public int number { get; set; }
        [Display(Name = "Марка")]
        [Required]
        public string brand { get; set; }
        [Display(Name = "Цвет")]
        [Required]
        public string colour { get; set; }
        [Display(Name = "Грузовая машина")]
        [Required]
        public Nullable<bool> type_car { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repairs_logbook> repairs_logbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trips_logbook> trips_logbook { get; set; }
    }
}
