//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication22.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class carsEntities1 : DbContext
    {
        public carsEntities1()
            : base("name=carsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<repairs> repairs { get; set; }
        public virtual DbSet<repairs_logbook> repairs_logbook { get; set; }
        public virtual DbSet<trips> trips { get; set; }
        public virtual DbSet<trips_logbook> trips_logbook { get; set; }
    
        public virtual ObjectResult<Request_Weight_Result> Request_Weight(Nullable<System.DateTime> start_time, Nullable<System.DateTime> end_time)
        {
            var start_timeParameter = start_time.HasValue ?
                new ObjectParameter("start_time", start_time) :
                new ObjectParameter("start_time", typeof(System.DateTime));
    
            var end_timeParameter = end_time.HasValue ?
                new ObjectParameter("end_time", end_time) :
                new ObjectParameter("end_time", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request_Weight_Result>("Request_Weight", start_timeParameter, end_timeParameter);
        }
    
        public virtual ObjectResult<Request2_Repairs_Result> Request2_Repairs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Request2_Repairs_Result>("Request2_Repairs");
        }
    }
}
