//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class trips_logbook
    {
        public int idtrip_logbook { get; set; }
        [Display(Name = "Рейс")]
        public int trips_idtrip { get; set; }
        [Display(Name = "Номер машины")]
        public int cars_number { get; set; }
        [Display(Name = "Дата и время начала рейса")]
        [Required]
        public Nullable<System.DateTime> start_time_trip { get; set; }
        [Display(Name = "Дата и время окончания рейса")]
        [Required]
        public Nullable<System.DateTime> end_time_trip { get; set; }
        [Display(Name = "Вес груза")]
        [Required]
        public Nullable<float> weight { get; set; }

        [Display(Name = "Номер машины")]
        public virtual cars cars { get; set; }
        [Display(Name = "Рейс")]
        public virtual trips trips { get; set; }
    }
}
