//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class trips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trips()
        {
            this.trips_logbook = new HashSet<trips_logbook>();
        }
    
        public int idtrip { get; set; }

        [Display(Name = "Начальный пункт")]
        [Required]
        public string start_point { get; set; }

        [Display(Name = "Конечный пункт")]
        [Required]
        public string end_point { get; set; }
        

        [Display(Name = "Расстояние между пунктами")]
        [Range(0, 999999, ErrorMessage = "Некорректно введено расстояние")]
        [Required]
        public Nullable<float> distance { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trips_logbook> trips_logbook { get; set; }
    }
}
